export const PRODUCT_COLORS: Record<string, string[]> = {
  'SMG-S24U':     ['black', 'white'],
  'SMG-A25':      ['black', 'blue'],
  'GPX-8A':       ['black', 'white', 'blue'],
  'APL-I15PM':    ['black', 'white', 'blue'],
  'XMI-RN13P5G':  ['black', 'blue'],
  'APL-IP13-128': ['black', 'white', 'blue', 'green'],
  'XIA-RN13':     ['black', 'blue', 'green'],
  'XMI-14':       ['black', 'white', 'green'],
  'SMG-A35':      ['black', 'white', 'blue'],
  'XMI-R13C':     ['black', 'white', 'blue', 'green'],
  'XMI-13TPro':   ['black'],
  'SMG-A05S':     ['black', 'white', 'green'],
  'SMG-S23FE':    ['black', 'green'],
  'MTE-EDGE50PRO':['black'],
  'SNY-XPERIA1V': ['black'],
  'MTO-G24':      ['black', 'green'],
  'OPP-A18':      ['blue'],
  'OPP-R11F':     ['blue', 'green'],
  'XIA-R12':      ['blue'],
}
