export const PRODUCT_COLORS: Record<string, string[]> = {
  'SMG-S24U':      ['negro', 'blanco'],
  'SMG-A25':       ['negro', 'azul'],
  'GPX-8A':        ['negro', 'blanco', 'azul'],
  'APL-I15PM':     ['negro', 'blanco', 'azul'],
  'XMI-RN13P5G':   ['negro', 'azul'],
  'APL-IP13-128':  ['negro', 'blanco', 'azul', 'verde'],
  'XIA-RN13':      ['negro', 'azul', 'verde'],
  'XMI-14':        ['negro', 'blanco', 'verde'],
  'SMG-A35':       ['negro', 'blanco', 'azul'],
  'XMI-R13C':      ['negro', 'blanco', 'azul', 'verde'],
  'XMI-13TPro':    ['negro'],
  'SMG-A05S':      ['negro', 'blanco', 'verde'],
  'SMG-S23FE':     ['negro', 'verde'],
  'MTE-EDGE50PRO': ['negro'],
  'SNY-XPERIA1V':  ['negro'],
  'MTO-G24':       ['negro', 'verde'],
  'OPP-A18':       ['azul'],
  'OPP-R11F':      ['azul', 'verde'],
  'XIA-R12':       ['azul'],
}
